### PR TITLE
Added additional query before generate new url

### PR DESCRIPTION
**Pull request by wachterjohannes**
__tasks:__

- [ ] gather feedback for my changes

__informations:__

| q                | a
| ---------------- | ---
| Fixed tickets    | none
| BC breaks        | none
| Documentation PR | none

### CODE REVIEW

**Comment by danrot** [comment]
What should this actually fix?

**Comment by wachterjohannes** [comment]
if you copy a internal link page into a new language - the `internal_link` property copies the path of the route instead of the uuid ... we should really think about remove this templates:

* excerpt
* internal_link
* external_link

but then we should think about an other possibility to override at least the excerpt template ...

**Comment by danrot** [comment]
Should the resource locator tag only be allowed on the `resource_locator` tag in general? Then I would put that in the validation somehow.

**Comment by wachterjohannes** [comment]
hmm it is used there to indicate the target ... maybe we should introduce a new tag for that!

**Comment by danrot** [comment]
But still, does it make sense to allow this tag on any content type which are not `resource_locator`?

**Comment by wachterjohannes** [comment]
no but this is a bigger refactoring ...

**Comment by danrot** [comment]
What happens now if this check fails? Nothing?

**Comment by wachterjohannes** [comment]
the unresolved content will be copied - the uuid

**Comment by wachterjohannes** [comment]
@danrot should i make it mergeable?

**Comment by danrot** [comment]
Hm, still don't feel safe about it... But you should at least implement a test, so that this problem won't reappear in @dantleech's refactoring

**Comment by wachterjohannes** [comment]
@dantleech this is also changing something in the content mapper!

**Comment by wachterjohannes** [comment]
@danrot i have addded a testcase!

**Comment by danrot** [comment]
@wachterjohannes So I've copied a page with the type internal link, which works now so far. But how can I access the new internal link afterwards on the website?

**Comment by danrot** [comment]
@c00n84 This fixes the problem with the copying, but the copied page won't be accessible afterwards, because it does not have an URL. I guess this won't be fixed before #1220 is addressed.

**Pull request merged**
