### PR TITLE
Fixed get contacts by usersystem function

### PR DESCRIPTION
**Pull request by turbo-ele**

### CODE REVIEW

**Comment by danrot** [comment]
I guess there was no test for this functionality?

**Comment by wachterjohannes** [comment]
@danrot you can be sure (:

**Comment by danrot** [comment]
Then this should be added. Actually we said we don't merge Bugfixes without tests anymore :wink:

**Comment by danrot** [comment]
Especially if the test would be that easy to write... Everytime we do this we have a higher chance to reintroduce bugs we have already fixed...

**Comment by danrot** [comment]
@turbo-ele @wachterjohannes Who adds the test?

**Pull request merged**
