### PR TITLE
Fetch user only if an entity with UserBlameInterface is detected within UserBlameSubscriber

### LINKED ISSUE #1509: UserBlameSubscriber throws an exception on flush with users that don't implement UserInterface
I have separate users within my app that do not implement the Sulu `UserInterface`; when logged in as one of these users and making changes to an entity that does not implement `UserBlameInterface` I get the following `RuntimeException`…

> Expected user object to be an instance of (Sulu) UserInterface. Got "OSX\Bundle\ShopBundle\Entity\Customer"

It looks like this is happening due to the subscriber getting the user before it has found an entity that implements `UserBlameInterface`…

https://github.com/sulu-io/sulu/blob/develop/src/Sulu/Component/Persistence/EventSubscriber/ORM/UserBlameSubscriber.php#L123

### PR DESCRIPTION
**Pull request by kriswillis**
__Information__

| Q                | A
| ---------------- | ---
| Fixed tickets    | Fixes #1509 
| BC breaks        | None
| Documentation PR | N/A

### CODE REVIEW

**Comment by danrot** [comment]
@kriswillis if you would add a test, and branch from master, I would release that as a hotfix release :-)

**Comment by chirimoya** [comment]
@kriswillis still relevant? We are currently planing the 1.1 release. If you could finish this PR we can include it. THX

**Comment by kriswillis** [comment]
@chirimoya Yes, still relevant - added tests, awaiting review :)

**Comment by danrot** [comment]
Looks fine, but the tests didn't run for a reason... Maybe you can rebase, and push again? Maybe the tests will run this time :-)

**Pull request merged**
