### PR TITLE
Added custom filter for lists

### PR DESCRIPTION
**Pull request by michaelzangerle**
__Tasks:__
- [x] done
- [ ] got feedback

__Informations:__

| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| Tests pass?   | yes
| Fixed tickets | none
| Doc           | https://github.com/sulu-io/sulu-docs/pull/43

__Requires:__
- https://github.com/massiveart/husky/pull/494
- https://github.com/massiveart/husky/pull/498

### CODE REVIEW

**Comment by michaelzangerle** [comment]
Added issue for filter operators (starts with, ends with) https://github.com/sulu-io/sulu/issues/1352

**Comment by wachterjohannes** [comment]
image

cannot delete a operator if there is no field selected

**Comment by wachterjohannes** [comment]
add the private field as column to list

**Comment by wachterjohannes** [comment]
open task before integrating into sulu-standard:

* Save current selected filter in user settings
* Begin and Ends operator for string

this should be added before the PR in sulu-standard (https://github.com/sulu-io/sulu-standard/pull/441) will be merged

**Comment by michaelzangerle** [comment]
private field as column in the list needs https://github.com/massiveart/husky/issues/499

**Comment by michaelzangerle** [comment]
Fixed bug when deleting an empty condition in https://github.com/sulu-io/sulu/commit/1fb652c79a22f62a6e3a4f39d48321554ee75471

**Pull request merged**
