### PR TITLE
[FEATURE] Added setter for id for testing purposes

### PR DESCRIPTION
**Pull request by christianbader**

### CODE REVIEW

**Comment by turbo-ele** [comment]
ack

**Comment by patkar** [comment]
:-1:

**Comment by wachterjohannes** [comment]
@turbo-ele also :-1: why you have added this?

**Comment by wachterjohannes** [comment]
@christianbader is this only for testing? this double :-1: :-1: in tests you could really use reflection and why should not add stuff to core for testing purpose!

**Comment by christianbader** [comment]
@wachterjohannes i will fix it asap

**Pull request merged**
