### PR TITLE
Added cleanup resource-locator history command

### LINKED ISSUE #1239: Make command for cleaning url history before online going
I want to clean my url history before a website is going live. Often the clients move pages, change titles and the urls and so there are many entries in the url history which aren't needed.

### PR DESCRIPTION
**Pull request by wachterjohannes**
__tasks:__

- [ ] gather feedback for my changes

__informations:__

| q                | a
| ---------------- | ---
| Fixed tickets    | fixes #1239
| BC breaks        | none
| Documentation PR | none

### CODE REVIEW

**Comment by danrot** [comment]
Changelog is missing, and I would also add a test (we should test commands more often...)

**Comment by danrot** [comment]
@wachterjohannes Do you test if the routes are actually removed? I only see that the output is tested, which is not so important at all.

**Comment by wachterjohannes** [comment]
@danrot i have added checks on the repsitory

**Comment by danrot** [comment]
ACK :stuck_out_tongue:

**Comment by wachterjohannes** [comment]
sorry to many open tabs (:

**Pull request merged**
