### PR TITLE
Feature/refactoring order

### PR DESCRIPTION
**Pull request by dantleech**
This PR contains an optimization, but the commit needs to be cherrypicked onto a develop.

### CODE REVIEW

**Comment by chirimoya** [comment]
What is this PR about?

**Comment by dantleech** [comment]
@chirimoya as mentioned in the description, it contains an optimization. The only commit is the last one, I need to cherry pick it onto develop.

**Comment by danrot** [comment]
@dantleech Can you maybe close this PR, and create a new one with the right commit? In case your change is still valid.

**Comment by dantleech** [comment]
The fix is already in develop since 16th July.

**Pull request closed without merging**
