### PR TITLE
ENHANCEMENT: Change Role naming to keep symfony2 convention

### LINKED ISSUE #1159: Keep Symfony2 Standards for Roles names
Copied from sulu/standard. Just for the PR.
Maybe it is a good idea to keep symfony2 standards in the Role names. The BaseRole Entity on the SecurityBundle use SULU_ROLE_ in the getIdentifier and getRole function. Using ROLE_SULU_ would be compatible with Symfony2 and they could be use for the firewall.

### PR DESCRIPTION
**Pull request by sRmarcos**
[short description]:

__tasks:__

- [ ] fix #1159 

__informations:__

| q                | a
| ---------------- | ---
| Fixed tickets    | fixes #1159 
| BC breaks        | yes
| Documentation PR |

### CODE REVIEW

**Comment by chirimoya** [comment]
@danrot ... can you have a look.

**Comment by danrot** [comment]
Looks good, there is just a small issue... @sRmarcos This is a BC break, since the acl system of symfony uses this role name to check the permission, which means the developer has to adjust the values in the `acl_security_identities` table. If you add this to the `UPGRADE.md` file we can merge this.

**Comment by sRmarcos** [comment]
Yes, you are right. I update the UPGRADE.md file and add a small sql snippet also.

**Comment by danrot** [comment]
Thank you :-)

**Pull request merged**
