### PR TITLE
Added soft-delete

### LINKED ISSUE #921: Implement "soft delete" for users/contacts
Since some data (e.g. products) depending on existing users, deleting a user may cause serious results.
Thus, a user should only be "soft deletable".

For implementation details see:
https://github.com/l3pp4rd/DoctrineExtensions/blob/master/doc/softdeleteable.md

### PR DESCRIPTION
**Pull request by wachterjohannes**
__tasks:__

- [ ] test coverage
- [ ] submit changes to the documentation

__informations:__

| q                | a
| ---------------- | ---
| Fixed tickets    | fixes #921 
| Related PRs      | https://github.com/sulu-io/sulu-standard/pull/564
| BC breaks        | TODO
| Documentation PR | TODO

### CODE REVIEW

**Comment by dantleech** [comment]
Soft deletes are generally considered to be evil and can be replaced by versioning / audit logging..

**Comment by danrot** [comment]
@dantleech But in this case they are needed, because we end up in some inconsistent state otherwise. Imagine sulu is also used as a blog, even if a user is deleted, I want the author to be displayed correctly.

**Comment by alexander-schranz** [comment]
@danrot think it should be configurable because if i have a login on the website and the user is deleted all his data need to be deleted because of data protection.

**Comment by dantleech** [comment]
Then you shouldn't be *allowed* to delete a user that is associated with a
blog. You should simply desactivate the user. If the user still exists
for the system, it still exists.

If the user really wants to *delete* the user so that they were never
there, the Blog Posts should be de-associated from the user.

**Comment by webmozart** [comment]
I agree with @dantleech. Deactivating a user sounds more appropriate here.

**Comment by webmozart** [comment]
@wachterjohannes Should we close this issue?

**Comment by wachterjohannes** [comment]
i think so because it is not ready and we have a lot of problems with this.

**Pull request closed without merging**
