### PR TITLE
[WIP] Added DoctrineFieldDescriptorBuilder

### PR DESCRIPTION
**Pull request by danrot**
__Tasks:__

- [ ] test coverage
- [ ] gather feedback for my changes
- [ ] submit changes to the documentation

__Informations:__

| Q             | A
| ------------- | ---
| Tests pass?   | no
| Fixed tickets | none
| BC Breaks     | none
| Doc           | TODO

### CODE REVIEW

**Comment by chirimoya** [comment]
@danrot should be merged?

**Comment by danrot** [comment]
No, that's the started work on the field descriptors, which is not finished (it's just here that it doesn't get lost). You also said we should do that in a sylius like way, using configuration files instead of code. But I would let this one open, will be needed as reference, once we start to work on this again.

**Comment by chirimoya** [comment]
@danrot ;-)

**Comment by danrot** [comment]
I guess we will solve this in a different way, with some config files, as we've already discussed, so I close this issue.

**Pull request closed without merging**
