### PR TITLE
[WIP] Added exception handling for missing properties

### PR DESCRIPTION
**Pull request by chirimoya**

### CODE REVIEW

**Comment by danrot** [comment]
@wachterjohannes What's this PR about? And can you finish reviewing it?

**Comment by wachterjohannes** [comment]
@danrot i have to discuss this with thomas ... seems to be forgotten (=

**Comment by danrot** [comment]
@wachterjohannes Did you discuss it? ;-)

**Comment by dantleech** [comment]
@wachterjohannes ping

**Comment by wachterjohannes** [comment]
this was replaced by the document manager

**Comment by wachterjohannes** [comment]
this was replaced by the document-manager

**Pull request closed without merging**
