### PR TITLE
Fix consistency into di definition parameters

### PR DESCRIPTION
**Pull request by cbastienbaron**
fix consistency into di definition parameters :
Classes hardcoded replaced by parameters to code consistency

__tasks:__

- [ x ] consistency into di definition

__informations:__

| q                | a
| ---------------- | ---
| Fixed tickets    | none 
| Related PRs      | none
| BC breaks        | none
| Documentation PR | none

### CODE REVIEW

**Comment by wachterjohannes** [comment]
thanks for contribution! but we have decided to go the other way around in the future and we dont want this parameters for new features but keep them to not break the BC. this is because symfony also will drop the class parameter with 3.0. @danrot do you have the link where they announved this?

**Comment by cbastienbaron** [comment]
Haaa i wasn't aware of this. ;(  thks for information @wachterjohannes  ;)

do you prefer to replace in *.xml
`class="%my.class%"` by `class="My\Class"` ? 

or for moment keep like this ?

**Comment by wachterjohannes** [comment]
hmm i think we wont replace all class parameter to avoid bc breaks if someone uses this parameters to extend sulu. @danrot what do you think about that?

**Comment by danrot** [comment]
@wachterjohannes Yeah, that was what we thought... We should remove all the parameters at some point, but I think that won't be before 2.0. It's also not too bad to have it this way (the performance impact due to the bigger container is probably not sooo big).

**Comment by cbastienbaron** [comment]
sounds good, guess we can close this :smile:

**Pull request closed without merging**
