### PR TITLE
Improved the PR template

### PR DESCRIPTION
**Pull request by webmozart**
| Q | A
| --- | ---
| Bug fix? | no
| New feature? | no
| BC breaks? | no
| Deprecations? | no
| Fixed tickets | -
| Related issues/PRs | #2090
| License | MIT
| Documentation PR | -

#### What's in this PR?

I improved the PR template to advise the user to remove the "Why?" section if an issue exists and is referenced in the PR table. The description of that issue should suffice as clarification.

#### Why?

At the moment, it's not clear to what extent an issue should be described again under "Why?" when creating a PR that fixes the issue.

### CODE REVIEW

**Comment by chirimoya** [comment]
+1

**Comment by wachterjohannes** [comment]
thats not a good idea in my opinion we should have more in our PR but it should be possible to remove something. i would revert that /cc @danrot @chirimoya @webmozart

**Comment by danrot** [comment]
@wachterjohannes Why shouldn't this be a good idea? The issue already describes what is failing, and this is the obvious reason why the PR is there. Just have a look at your description in https://github.com/sulu-io/sulu/pull/2090

**Comment by wachterjohannes** [comment]
yeah but thats only a very small PR look at this where i have used other headers to discribe the PR full https://github.com/sulu-io/sulu/pull/2107

**Comment by wachterjohannes** [comment]
for me such a PR template is not really helpful i liked the template before that merge. but ok i will not intervent for this anymore since i am pretty much the same with this opinion :)

**Comment by webmozart** [comment]
@wachterjohannes Are you talking about this PR specifically or the new template in general? What issue do you have?

**Comment by wachterjohannes** [comment]
ou i think i have overseen something yesterday ... i thought you removed all the other sections ... sorry my fault (:

**Pull request merged**
