### PR TITLE
[WIP] Renaming getContent to getPropertyContainer

### PR DESCRIPTION
**Pull request by dantleech**
Renaming `StructureBehavior#getContent` to `StructureBehavior#getPropertyContainer` as that is what it actually does.

### CODE REVIEW

**Comment by dantleech** [comment]
`structure` probably makes more sense than `propertyContainer`. In which case `[Managed]PropertyContainer[Interface]` should be renamed `[Managed]Structure[Interface]`.

So accessing a property might look like

````php
$document->getStructure()->getProperty('asd');
// or if serialized
$data['structure']['asd'];
// as opposed to
$data['propertyContainer']['asd']
````

This would also give `StructureMetadata` a sensibly named counterpart.

The `StructureInterface` would represent the data of a structure.

**Comment by dantleech** [comment]
@chirimoya @danrot does the above comment make sense to you?

So currently we have

````
$document->getPropertyContainer()->getProperty('arf');
````

Where the property container is `PropertyContainerInterface`.

I propose to rename it to `StructureInterface`, so `$document->getStructure()`.

**Comment by danrot** [comment]
Yeah, definitely makes sense to me.

**Comment by dantleech** [comment]
I did this again in a different branch and it is already merged.

**Pull request closed without merging**
