### PR TITLE
Inheritdoc fixes

### PR DESCRIPTION
**Pull request by GrahamCampbell**
This should fix StyleCI failing on you.

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Ping @wachterjohannes. Please review https://styleci.io/analyses/8PBxPq. You appear to have a bug in your code. StyleCI is now picking this up for you. :)

**Comment by danrot** [comment]
Looks like there was a lot changed in StyleCI... Thank you for the fix, I will do the other ones in a separate PR.

**Comment by GrahamCampbell** [comment]
Great. :)

**Comment by wachterjohannes** [comment]
@GrahamCampbell looks good ... seems like that `inheritdoc` was generated by an older intellij version with an uppercase `D`. but now its generated correct ...

**Pull request merged**
