### PR TITLE
Adding PHP 5.6 and HHVM to Travis.

### PR DESCRIPTION
**Pull request by h4cc**
Just test if 5.6 and HHVM would work ...

### CODE REVIEW

**Comment by danrot** [comment]
@h4cc Looks like there are still a lot of fails in HHVM, and atm we don't have time to fix this... But having PHP 5.6 as a build job sounds almost mandatory to me. So if you remove HHVM again this is fine to merge for me.

**Comment by chirimoya** [comment]
maybe we should move hhvm to `allow_failures`

**Comment by h4cc** [comment]
Ok, but now you know it may not work with HHVM :|

Add it to `allow_failures` if you like to.

**Comment by danrot** [comment]
Thank you anyway :smiley:

**Pull request closed without merging**
