### PR TITLE
Make view a default parameter

### PR DESCRIPTION
**Pull request by dantleech**
This PR makes places the "view" template into the request as a default parameter, allowing it to be modified during the `kernel.request` event.

### CODE REVIEW

**Comment by alexander-schranz** [comment]
if we make in the indexAction a BC Break it would be good to add also `Request $request` as first param

```
indexAction(Request $request, ....
```

normally when you extend from this controller to add something you need to use `$this->getRequest()` which is deprecated function.

**Comment by wachterjohannes** [comment]
related issue https://github.com/sulu-io/sulu/issues/503

**Comment by dantleech** [comment]
Yeah, I think using `Request` would be better.

**Comment by danrot** [comment]
Why do you need this change?

**Comment by chirimoya** [comment]
ping @dantleech @alexander-schranz

**Comment by webmozart** [comment]
Closing due to lack of feedback.

**Pull request closed without merging**
