### PR TITLE
Fixed routing when clicking of the data-navigation search-icon

### LINKED ISSUE #1876: Media selection overlay bug when clicking on search icon
Reproduce:
1. Got to a content page and click on a "add media" button
2. In the overlay search for a collection 
3. click on the search-icon
4. the overlay closes and you get redirected to /admin/#

bildschirmfoto 2015-12-14 um 17 49 21

### PR DESCRIPTION
**Pull request by wachterjohannes**
| Q | A
| --- | ---
| Bug fix? | yes
| New feature? | no
| BC breaks? | no
| Deprecations? | no
| Fixed tickets | fixes #1876 
| Related issues/PRs | https://github.com/massiveart/husky/pull/613
| License | MIT
| Documentation PR | none

#### What's in this PR?

When clicking on the search icon in media-selection overlay or collection view (described in the PR) the admin links to `/admin/#` instead of searching for the given term.

### CODE REVIEW

**Comment by danrot** [comment]
This PR doesn't contain the changes from https://github.com/massiveart/husky/pull/613, and styleci fails :wink:

**Comment by wachterjohannes** [comment]
@danrot fixed

**Comment by danrot** [comment]
The remove icon in the search field has some style problems:
image

**Comment by wachterjohannes** [comment]
@danrot the mentioned bug is fixed now

**Comment by danrot** [comment]
Needs a rebase in husky :/

**Comment by wachterjohannes** [comment]
@danrot this should now be good - both rebase

**Pull request merged**
