### PR TITLE
[WIP][FEATURE] #307 allow meta title in template content type parameter + content type values + Select Content Type

### PR DESCRIPTION
**Pull request by alexander-schranz**
__Tasks:__

- [ ] test coverage
- [ ] gather feedback for my changes

__Informations:__

| Q             | A
| ------------- | ---
| Feature?   | yes #307 
| Tests pass?   | none
| Fixed tickets | parts of #424 
| BC Breaks     | none
| Doc           | none

### CODE REVIEW

**Comment by danrot** [comment]
@alexander-schranz What's the current state of this PR?

**Comment by chirimoya** [comment]
@alexander-schranz, @danrot ping

**Comment by danrot** [comment]
I guess a lot of the code here can be dumped because of https://github.com/sulu-io/sulu/pull/789 (we decided not to do this value stuff, and use translateable params instead, since the SmartContent needed something similar). So I would say that we select content type from this and create a separate PR for it.

**Comment by chirimoya** [comment]
@alexander-schranz @danrot should we close this PR?

**Comment by danrot** [comment]
I think we already solved this configuration problem in here in a different way in https://github.com/sulu-io/sulu/issues/789. I don't know if it is faster to adapt this PR, or create a new one.

**Comment by alexander-schranz** [comment]
will close this PR because think its faster when working on #424 to create a new branch from dev

**Pull request closed without merging**
