### PR TITLE
fixed snippet assignment delete

### PR DESCRIPTION
**Pull request by danrot**
__tasks:__

- [ ] gather feedback for my changes

__informations:__

| q                | a
| ---------------- | ---
| Fixed tickets    | fixes part of #898 
| BC breaks        | none
| Documentation PR | none

### CODE REVIEW

**Comment by wachterjohannes** [comment]
@danrot missing changelog

**Comment by wachterjohannes** [comment]
image

its not really related to that but when i:

* select all snippets
* and the deselect it over the itembox

the "select all" checkbox is check ... perhaps a issue would be enough

**Comment by wachterjohannes** [comment]
the rest works and code is OK

**Comment by danrot** [comment]
Fixed the datagrid bug in https://github.com/massiveart/husky/pull/490

**Comment by wachterjohannes** [comment]
@danrot perfect could you please update this PR?

**Pull request merged**
