### PR TITLE
Fixed translation code length in database schema

### LINKED ISSUE #1997: Longer translation codes than 60 characters
I think it would be nice if translations-codes could be longer than 60 chars, as they can be longer when we use namespaced translation-codes

### PR DESCRIPTION
**Pull request by wachterjohannes**
| Q | A
| --- | ---
| Bug fix? | no
| New feature? | no
| BC breaks? | yes (see UPGRADE)
| Deprecations? | no
| Fixed tickets | fixes #1997 
| Related issues/PRs | none
| License | MIT
| Documentation PR | none

#### What's in this PR?

This PR extend the maximum length of translation codes.

### CODE REVIEW

**Comment by danrot** [comment]
Can you also add a `max-length` to the field in the UI? It's just a question of time until somebody even exceeds that limit.

**Comment by wachterjohannes** [comment]
the translation UI isnt used currently and has to be refactored in the future - so no i have not added it (:

**Comment by danrot** [comment]
Ah, sry, I thought this is about categories :confused:

**Comment by wachterjohannes** [comment]
for the categories there is another PR which adds the max-length there

**Pull request merged**
