### PR TITLE
Remove Group By from Category List Representation

### PR DESCRIPTION
**Pull request by carltongibson**
Fixes https://github.com/sulu-io/sulu-standard/issues/522

Removes `addGroupBy` call causing failures on PostgreSQL. Tests pass without it.

### CODE REVIEW

**Comment by danrot** [comment]
Please add a line to the `CHANGELOG.md` file.

**Comment by danrot** [comment]
This one looks fine, thank you :smiley:

**Comment by danrot** [comment]
But can you maybe create the PR against the `bugfix/postgres` branch?

**Comment by carltongibson** [comment]
@danrot — no problem — I was thinking that :-)

(I'll leave the change log entries a single PR since I'm going to have to resolve the merge conflict...)

**Comment by carltongibson** [comment]
Closing in favour of #1742

**Pull request closed without merging**
