### PR TITLE
added parameter to show toggler instead of checkbox

### PR DESCRIPTION
**Pull request by danrot**
__tasks:__

- [ ] submit changes to the documentation

__informations:__

| q                | a
| ---------------- | ---
| Fixed tickets    | parts of #1741
| Related PRs      | https://github.com/massiveart/husky/pull/593
| BC breaks        | none
| Documentation PR | https://github.com/sulu-io/sulu-docs/pull/149

### CODE REVIEW

**Comment by wachterjohannes** [comment]
@danrot should that style not be implemented in select content type too?

**Comment by wachterjohannes** [comment]
style-ci fails

**Comment by wachterjohannes** [comment]
build files missing for admin- and content-bundle

**Comment by wachterjohannes** [comment]
please rebase it to avoid the failing testcase for `ch`

**Comment by danrot** [comment]
@wachterjohannes It should also be implemented in the select content type, but there are too many obstacles, so we decided to leave that for now. Your other points are fixed now.

**Comment by wachterjohannes** [comment]
i have found an issue with the toggler.

* add the new param to the example
* create a new page with the `default` template
* change to `example` template
* set toggler
* save
* reload page

after that the toggler is deactivated.

**Comment by danrot** [comment]
@wachterjohannes fixed it

**Comment by danrot** [comment]
@wachterjohannes Solved parts of the latest issue, created a new issue for the complete issue: https://github.com/sulu-io/sulu/issues/1929

**Pull request merged**
