### PR TITLE
Added cascade options to account and contact

### PR DESCRIPTION
**Pull request by wachterjohannes**
__tasks:__

- [ ] gather feedback for my changes

__informations:__

| q                | a
| ---------------- | ---
| Fixed tickets    | none
| BC breaks        | none
| Documentation PR | none

### CODE REVIEW

**Comment by wachterjohannes** [comment]
@danrot this should be merged in 1.0 (master) and 1.1 (develop)

**Comment by wachterjohannes** [comment]
no not in master

**Comment by danrot** [comment]
Isn't it possible to put these options on the foreign keys? Then it would be more performant, since the database already handles this, and it would also be correct if somebody deletes contacts using SQL.

And does that mean that these entities weren't deleted?

**Comment by wachterjohannes** [comment]
yes they wont be deleted (:

**Pull request merged**
