### PR TITLE
Improved test speed

### PR DESCRIPTION
**Pull request by dantleech**
Improve speed (and hopefully stability) of behat tests:

- Use HTTP authentication for login (by installing custom `config.local.yml`
- Use "refresh" instead of "visiit" if the current URL is the same as the requested one.

### CODE REVIEW

**Comment by dantleech** [comment]
See https://github.com/sulu-io/sulu-standard/pull/436

**Comment by danrot** [comment]
@dantleech Does this work?

**Comment by dantleech** [comment]
It *could* work. It doesn't currently work.

**Comment by danrot** [comment]
Was this because firefox was not able to correctly handle the http authentication? Then we could close this PR, couldn't we?

**Comment by dantleech** [comment]
It worked locally on selenium. But IIRC it was something like that. It would be a significant speed increase I believe. So I wouldn't close it unless there is something better, but its up to you guys.

**Comment by webmozart** [comment]
@dantleech What's the status here? Close or merge?

**Comment by dantleech** [comment]
Lets just close it.

**Pull request closed without merging**
