### PR TITLE
Combined PostgreSQL Fixes

### PR DESCRIPTION
**Pull request by carltongibson**
Fixes test failures for PostgreSQL

* [x] CategoryBundle
* [x] ContactBundle
* [x] TagBundle
* [ ] MediaBundle
* [ ] ResourceBundle
* [ ] SecurityBundle
* [ ] TranslateBundle
* [ ] CHANGELOG.md Entry

### CODE REVIEW

**Comment by carltongibson** [comment]
@danrot I need some input on `SecurityBundle` — there's a couple of tests failing because `$role->getPermissions()` is not ordered. We can add that ordering by adjusting the entity, or adjust the tests. 
What do you think? 

E.g.
```
1) Sulu\Bundle\SecurityBundle\Tests\Functional\Controller\RoleControllerTest::testPut
Failed asserting that false matches expected true.

sulu/sulu/src/Sulu/Bundle/SecurityBundle/Tests/Functional/Controller/RoleControllerTest.php:318
```

If you look there you'll see the assertions are made against the expected order.

**Comment by danrot** [comment]
@carltongibson I'd say if it doesn't screw up the role screen in the admin interface (see the screenshot), I would go for not checking for the order.
image

**Comment by carltongibson** [comment]
@danrot Same issue comes up with `Filter::conditionGroups`. 

Simplest thing for me would be to add the ORM Order By in the entity definition (which wouldn't affect the screen, since that's the order MySQL is applying under the hood anyway — and for which the tests are written.)

**Comment by danrot** [comment]
@carltongibson Well, as said, we were already having these kind of issues, and solved it that way once. However, we removed it again, IIRC because of some performance issues. Can you make sure there are none, before implementing it this way? (could imagine that MySQL is a lot faster if not ordering the result, also if the result of the ordering would be the same).

**Comment by carltongibson** [comment]
@danrot — Can anyone tell me more there? Why is this not explained by a missing index or such? — There shouldn't be a performance issue such that you can't use sort.

It might be worth making the obvious fix and comparing the build times. From there I can investigate.

**Comment by danrot** [comment]
@carltongibson I think nobody investigated that further, we just ditched the order by clause because of this.

Just comparing build times is probably too less, because they are also influenced by other stuff. I would try to compare the resulting SQL queries.

**Comment by danrot** [comment]
@carltongibson Ok, I've still found some occurences of these `order-by` tags in some xml mappings, so I think that's fine for the moment. If it gets a performance issue, we can tackle that later.

**Comment by carltongibson** [comment]
@danrot OK thanks for the follow-up. I'll do it this way for now — either way if we can get Postgres "green" then at least we've got test coverage for changing things. 

I was looking at reworking the tests — I don't think it would be too bad: my _least disruptive_ approach would just be to sort the results in PHP prior to making the assertions. (We're only looking at result sets with <5 members so it's very little cost to it.)

**Comment by danrot** [comment]
What we have usually done until now is to pass `true` as second parameter to `json_decode`, so that it returns an array. This way you could use `assertContains` instead of `assertEquals`, which also gives better error messages.

**Comment by carltongibson** [comment]
OK. That would work for some of the cases. Others, like the security bundle, is checking individual attributes on the `object at index` — so it's important to get the right one :-) 

I'll have a look and do something, hopefully sensible. 

(It would be nice to see the performance issue in hand: I appreciate for ORDER BY `id` isn't not really important but eventually we will need to sort in earnest; it would be nice to know that's not going to be a problem.)

**Comment by danrot** [comment]
Yeah, would be nice if you could try to compare these requests. And if it is not a big performance issue just add the order by clauses to the xml mapping.

**Comment by carltongibson** [comment]
Hey @danrot. I've rebased the changes here from the latest `develop` and I've started seeing a strange issue on the Postres build:

```                                                                               
  [Doctrine\DBAL\Exception\TableExistsException]                               
  An exception occurred while executing 'CREATE INDEX key_idx ON me_collectio  
  n_types (collection_type_key)':                                              
  SQLSTATE[42P07]: Duplicate table: 7 ERROR:  relation "key_idx" already exis  
  ts                                                                          
```      

Does this ring any bells with you?

**Comment by carltongibson** [comment]
(Bar the new errors) the remaining issues I'm seeing are all the same PostgreSQL ordering problems — they're all demonstrating the same non-deterministic behaviour on separate test runs. 

To address these I will need to specify the ordering at the ORM level — the groupings are multiple levels deep (Filter Condition Groups and User Roles) so it's not feasible to manually sort at each stage in the test cases. 

(e.g. `FilterControllerTest` first creates and then fetches filters with nested condition groups so we're relying on a double ordering for the test to pass.)

**Comment by danrot** [comment]
I think we've put a new index somewhere, but I can't recall any problems with that. Filtering on the ORM level is fine, as we already said somewhere else.

**Comment by danrot** [comment]
PR is merged, GitHub doesn't realize because I had to rebase.
@carltongibson You can start your next steps from `bugfix/postgres` now, but please tell me before, then I can rebase once more right before you start, so that you have less conflicts.

**Pull request closed without merging**
